a

diff --git a/.github/actions/sf-deploy/action.yml b/.github/actions/sf-deploy/action.yml
--- a/.github/actions/sf-deploy/action.yml
+++ b/.github/actions/sf-deploy/action.yml
@@ -89,9 +89,18 @@ runs:
         sf project deploy start "${deployFlags[@]}"
     - name: Capture Deployment ID
       id: get-deploy-id
-      shell: bash
       run: |
+        echo "Running sfdx force:source:deploy:report"
         DEPLOY_ID=$(sfdx force:source:deploy:report --json | jq -r .result.id)
+        
+        if [ -z "$DEPLOY_ID" ]; then
+          echo "Error: Deployment ID is empty"
+          sfdx force:source:deploy:report --json
+          exit 1
+        fi
+        
+        echo "DEPLOY_ID: $DEPLOY_ID"
+        
         echo "deploy-id=$DEPLOY_ID" >> $GITHUB_ENV
         echo "::set-output name=deploy-id::$DEPLOY_ID"
 
